Main articles section
XashDM/SportHub pull request #25
Opened 2023-05-09 17:34 UTC by Adeodonne

add main articles section
fix menus

2023-05-10 14:40 UTC, Oleh-Kril requested changes

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/pages/Admin/components/AdminPage.js
> +                        case "Home":
Move this to constants object

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/Surveys/components/Surveys.js
> +            <LableForModules label={"Surveys"} />
Add this for other modules (banners, shares...)  please

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AdminMainArticlesSection.js
> +                            selectedOrder={mainArticles[articleFormsCount].order}
refactor as const mainArticle = mainArticles[articleFormsCount]. And then use mainArticle.order... or something like that for not repeating yourself

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AdminMainArticlesSection.js
> +    useEffect(() =>{
Move useEffect under others useEffects (it will be easier to read and understand)

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AdminMainArticlesSection.js
> +            newList[articleFormsCount].isTheLast = articleFormsCount === newList.length - 1 && articleFormsCount !== MAX_MAIN_ARTICLES_AMOUNT - 1
Please add some comment where it's not obvious what happening in your code

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AdminMainArticlesSection.js
> +                            selectedOrder={mainArticles[articleFormsCount].order}
And consider making props the same name as here to do it all with unpacking syntax {...mainArticle}. This will reduce the amount of unneeded lines

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AdminMainArticlesSection.js
> +import React, {useEffect, useState} from 'react'
GENERAL RECOMMENDATION: Do you have any ideas how to make this component simpler / move some logic in children components

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AddMainArticle/components/AddMainArticle.js
> +                        width={"100%"}
don't like the idea of passing width as prop. Consider using containers with width that wrap autoCompletes. (those three with display flex and this one will be 100%)

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AddMainArticle/components/AddMainArticle.js
> +                        value={selectedCategory}
Need to discuss with @XashDM where to put the same data that you are passing to all this autocompletes

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminHeader/components/AdminHeader.js
> +                                        <div>Test Testenko</div> <img className={styles.open_profile_menu} src={process.env.PUBLIC_URL + '/icons/Polygon.svg'}  alt={""}/>
empty alt

2023-05-10 14:40 UTC, Oleh-Kril commented on SportHub/src/modules/AdminMainArticlesSection/components/AddMainArticle/components/AddMainArticle.js
> +    const [category, setCategory] = useState(selectedCategory)
Need to discuss this on scrum meeting with @XashDM

2023-05-13 18:05 UTC, XashDM approved these changes

2023-05-13 18:13 UTC, merged