make backend for main articles
XashDM/SportHub pull request #34
Opened 2023-05-30 18:45 UTC by Adeodonne

make backend for main articles
fix frontend for main articles

2023-05-30 19:17 UTC, Oleh-Kr requested changes
Backend - reviewed, Frontend - move to another PR for review

2023-05-30 19:17 UTC, Oleh-Kr commented on SportHub.Data/Entities/ArticleForAutocomplete.cs
> +public class ArticleForAutocomplete
I don't think it's a good idea to link it to Autocomplete because backend should not depend on frontend

2023-05-30 19:17 UTC, Oleh-Kr commented on SportHub.API/Controllers/ArticleController.cs
> +				var articlesForAutocomplete = await _articlesService.GetArticleForAutocompleteByLanguageIdAndPropertyIdAsync(languageId, "CategoryId", categoryId);
Again, link backend method to frontend autocomplete is a bad practice

2023-05-30 19:17 UTC, Oleh-Kr commented on SportHub.API/Controllers/MainArticlesController.cs
> +public class MainArticlesController : ControllerBase
My part of logic is in Article Controller we have to do something about it

2023-05-30 19:17 UTC, Oleh-Kr commented on SportHub.Business/Interfaces/IMainArticlesServices.cs
> +    Task<IEnumerable<ArticleForMainArticleForm>> GetMainArticlesWithAdditionalInformationByLanguageIdAsync(string languageId);
Name of Entity and of method is totally different. I would prefer something like GetMainArticlesWithDetails

2023-05-30 19:17 UTC, Oleh-Kr commented on SportHub.Business/Services/MainArticlesServices.cs
> +    public async Task CreateMainArticlesAsync(IEnumerable<MainArticle> mainArticles)
What if it will break in the meddle of foreach loop ?

2023-06-01 07:05 UTC, XashDM commented on SportHub.API/Controllers/ArticleController.cs
> +		public async Task<IActionResult> GetArticleByArticleIdAndLanguageIdAsync([FromQuery] string articleId, string languageId)
GetArticleById

2023-06-01 07:07 UTC, XashDM commented on SportHub.API/Controllers/ArticleController.cs
> +		public async Task<IActionResult> GetArticlesForAutocompleteByLanguageIdAndCategoryIdAsync([FromQuery] string languageId, string categoryId)
Do not mention autocomple, make single method for getting all articles

2023-06-01 07:14 UTC, XashDM commented on SportHub.API/Controllers/ArticleController.cs
> +				var articlesForAutocomplete = await _articlesService.GetArticleForAutocompleteByLanguageIdAndPropertyIdAsync(languageId, "SubCategoryId", subCategoryId);
Create object that encapsulates parameters

2023-06-01 07:28 UTC, XashDM commented on SportHub.Data/Repositories/ArticleRepository.cs
> +			return articles.AsEnumerable();
redundant

2023-06-01 07:29 UTC, XashDM commented on SportHub.Data/Repositories/ArticleRepository.cs
> +	public async Task<IEnumerable<Article>> GetArticlesByLanguageIdAndPropertyIdAsync(string languageId, string propertyIdName, string propertyId)
rewrite to support filtering

2023-06-18 11:46 UTC, XashDM commented on SportHub.API/MapperConfig.cs
> +                .ForMember(dest => dest.MainArticleId, opt => opt.MapFrom(src => Guid.NewGuid()))
Guid.NewGuid is part of business logic - move creation of new guid when you create main article

2023-06-18 11:48 UTC, XashDM approved these changes

2023-06-20 11:02 UTC, merged