admin page is refreshing when article is saved
XashDM/SportHub pull request #70
Opened 2023-07-16 19:42 UTC by malyna2

2023-07-16 19:50 UTC, XashDM commented
В чому була проблема?

2023-07-16 20:59 UTC, malyna2 commented
після збереження статті адмін потрапляє на сторінку зі всіма статтями, але ця сторінка не оновлюється, тому щоб побачити створену статтю треба було змінити категорію на іншу, а тоді повернути на попередню.

2023-07-17 06:49 UTC, Oleh-Kril commented
> після збереження статті адмін потрапляє на сторінку зі всіма статтями, але ця сторінка не оновлюється, тому щоб побачити створену статтю треба було змінити категорію на іншу, а тоді повернути на попередню.

все ще думаю що краще вручну перегрузити ніж програмно, бо юзер не зрозуміє що робиться що він зберіг артіклу, а йому сайт перегружається чомусь

2023-07-17 06:50 UTC, Oleh-Kril requested changes
Don't think it worth merging

2023-07-17 09:09 UTC, closed without merging